# Use Node.js base image
FROM node:lts

# Set working directory
WORKDIR /usr/src/app

# Copy package files
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy all files
COPY . .

# Expose the port (Make sure it matches the one in `docker-compose.yml`)
EXPOSE 3000

# Start the app
CMD ["npm", "run", "dev"]
